import { ThemeColors } from "../types/types";

export const themeColors: ThemeColors = {
  firstTheme: {
    "--background-color": "#3d4a83",
    "--background-result-color": "#192041",
    "--background-buttons-color": "#262e57",
    "--numbers-button-background-color": "#ffffff",
    "--numbers-button-text-color": "#39447c",
    "--numbers-button-border-color": "#bebebe",
    "--equal-button-background-color": "#d33c3c",
    "--equal-button-text-color": "#ffffff",
    "--equal-button-border-color": "#ac3131",
    "--rest-button-background-color": "#39447c",
    "--rest-button-text-color": "#ffffff",
    "--rest-button-border-color": "#2d355f",
    "--text-color": "#ffffff",
  },
  secondTheme: {
    "--background-color": "#cccccc",
    "--background-result-color": "#ffffff",
    "--background-buttons-color": "#aaaaaa",
    "--numbers-button-background-color": "#eeeeee",
    "--numbers-button-text-color": "#222222",
    "--numbers-button-border-color": "#bbbbbb",
    "--equal-button-background-color": "#ff6600",
    "--equal-button-text-color": "#ffffff",
    "--equal-button-border-color": "#b34700",
    "--rest-button-background-color": "#009999",
    "--rest-button-text-color": "#ffffff",
    "--rest-button-border-color": "#006666",
    "--text-color": "#222222",
  },
  thirdTheme: {
    "--background-color": "#3C2A21",
    "--background-result-color": "#261a0d",
    "--background-buttons-color": "#1A120B",
    "--numbers-button-background-color": "#E5E5CB",
    "--numbers-button-text-color": "#1A120B",
    "--numbers-button-border-color": "#D5CEA3",
    "--equal-button-background-color": "#937a01",
    "--equal-button-text-color": "#ffffff",
    "--equal-button-border-color": "#695700",
    "--rest-button-background-color": "#130d07",
    "--rest-button-text-color": "#D5CEA3",
    "--rest-button-border-color": "#130a00",
    "--text-color": "#E5E5CB",
  },
};
